create table public.prayer_days (
  id bigint generated by default as identity primary key,
  day integer not null unique check (day > 0),
  title text not null check (length(trim(title)) > 0),
  scripture_reference text not null,
  scripture_text text not null,
  preparation_text text not null,
  reflection_text text not null,
  response_prayer text not null,
  closing_text text not null,
  audio_path text not null check (audio_path !~ '^https?://'),
  duration_ms integer not null check (duration_ms > 0),
  sections jsonb not null check (jsonb_typeof(sections) = 'array'),
  has_production_audio boolean not null default true,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on column public.prayer_days.audio_path is
  'Path inside the public prayer-audio Storage bucket, for example day_001.m4a';

alter table public.prayer_days enable row level security;

grant select on table public.prayer_days to anon, authenticated;

create policy "Published prayer days are public"
on public.prayer_days
for select
to anon, authenticated
using (is_published = true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'prayer-audio',
  'prayer-audio',
  true,
  52428800,
  array['audio/mpeg', 'audio/mp4', 'audio/x-m4a', 'audio/wav']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Audio is publicly playable. Uploads, edits, and deletes remain restricted to
-- the Dashboard or a trusted backend using a secret/service-role key.
create policy "Prayer audio is publicly readable"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'prayer-audio');
